// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using lab_50_api_todo_list_core;

namespace lab_50_api_todo_list_core.Migrations
{
    [DbContext(typeof(TaskItemContext))]
    [Migration("20191011102834_m2")]
    partial class m2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099");

            modelBuilder.Entity("lab_50_api_todo_list_core.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CategoryName");

                    b.HasKey("CategoryID");

                    b.ToTable("Categories");

                    b.HasData(
                        new { CategoryID = 1, CategoryName = "Category1" },
                        new { CategoryID = 2, CategoryName = "Category2" },
                        new { CategoryID = 3, CategoryName = "Category3" }
                    );
                });

            modelBuilder.Entity("lab_50_api_todo_list_core.TaskItem", b =>
                {
                    b.Property<int>("TaskItemID")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CategoryID");

                    b.Property<DateTime?>("DateDue");

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<bool>("TaskDone");

                    b.Property<int?>("UserID");

                    b.HasKey("TaskItemID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("UserID");

                    b.ToTable("TaskItems");

                    b.HasData(
                        new { TaskItemID = 1, CategoryID = 2, DateDue = new DateTime(2019, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), Description = "Study", TaskDone = false, UserID = 1 },
                        new { TaskItemID = 2, CategoryID = 3, DateDue = new DateTime(2019, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified), Description = "Work", TaskDone = false, UserID = 3 },
                        new { TaskItemID = 3, CategoryID = 1, DateDue = new DateTime(2019, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified), Description = "Do nothing", TaskDone = false, UserID = 4 }
                    );
                });

            modelBuilder.Entity("lab_50_api_todo_list_core.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("UserName");

                    b.HasKey("UserID");

                    b.ToTable("Users");

                    b.HasData(
                        new { UserID = 1, UserName = "User1" },
                        new { UserID = 2, UserName = "User2" },
                        new { UserID = 3, UserName = "User3" },
                        new { UserID = 4, UserName = "User4" }
                    );
                });

            modelBuilder.Entity("lab_50_api_todo_list_core.TaskItem", b =>
                {
                    b.HasOne("lab_50_api_todo_list_core.Category", "Category")
                        .WithMany("TaskItems")
                        .HasForeignKey("CategoryID");

                    b.HasOne("lab_50_api_todo_list_core.User", "User")
                        .WithMany("TaskItems")
                        .HasForeignKey("UserID");
                });
#pragma warning restore 612, 618
        }
    }
}
